// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbukjobmomhawctjdqaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpidWtqb2Jtb21oYXdjdGpkcWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNDcyNzcsImV4cCI6MjA1NTcyMzI3N30.u8rXIdoGSesTl_gGjso6riWkXrBk2KF4AlwiPyoscfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);